src/main/java/model/CoffeeOrderItem.java
package model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

@Entity
@Table(name = "coffee_order_item")
public class CoffeeOrderItem {

	@Id
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;

	@ManyToOne
	@JoinColumn(name = "type_id")
	private CoffeeType coffeeType;

	@ManyToOne
	@JoinColumn(name = "order_id")
	private CoffeeOrder coffeeOrder;

	@Column(name = "quantity")
	private int quantity;

	@Transient
	private int freeQuantity;

	public CoffeeOrderItem() {
	}

	public CoffeeOrderItem(CoffeeType coffeeType, CoffeeOrder coffeeOrder) {
		this.coffeeType = coffeeType;
		this.coffeeOrder = coffeeOrder;
	}

	public BigDecimal getCost() {
		return coffeeType.getPrice().multiply(BigDecimal.valueOf(quantity - freeQuantity));
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CoffeeType getCoffeeType() {
		return coffeeType;
	}

	public void setCoffeeType(CoffeeType coffeeType) {
		this.coffeeType = coffeeType;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public CoffeeOrder getCoffeeOrder() {
		return coffeeOrder;
	}

	public void setCoffeeOrder(CoffeeOrder coffeeOrder) {
		this.coffeeOrder = coffeeOrder;
	}

	public int getFreeQuantity() {
		return freeQuantity;
	}

	public void setFreeQuantity(int freeQuantity) {
		this.freeQuantity = freeQuantity;
	}

}

src/main/java/model/CoffeeType.java
package model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "coffee_type")
public class CoffeeType {

	@Id
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;

	@Column(name = "name")
	private String name;

	@Column(name = "price")
	private BigDecimal price;

	@Column(name = "disabled")
	private String disabled;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getDisabled() {
		return disabled;
	}

	public void setDisabled(String disabled) {
		this.disabled = disabled;
	}

}

src/main/java/controller/ConfigController.java
package controller;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;

import model.ConfigParameter;
import service.ConfigService;

@ApplicationScoped
@ManagedBean
public class ConfigController {
	
	private ConfigService configService = new ConfigService();

	public ConfigParameter getFreeCupParameter() {
		return configService.getConfigParameter("n");
	}

	public ConfigParameter getDeliveryCostParameter() {
		return configService.getConfigParameter("m");
	}

	public ConfigParameter getFreeDeliveryParameter() {
		return configService.getConfigParameter("x");
	}

	public ConfigParameter getMaxCupsPerTypeParameter() {
		return configService.getConfigParameter("maxCupsPerType");
	}

}

src/main/java/controller/OrderController.java
package controller;

import java.util.List;
import java.util.stream.Collectors;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import context.ResourceBundleUTF8;
import model.CoffeeOrder;
import model.CoffeeOrderItem;
import service.CoffeeOrderService;
import service.exception.CoffeeOrderServiceException;

@SessionScoped
@ManagedBean
public class OrderController {

	@ManagedProperty(value = "#{configController}")
	private ConfigController configController;

	private CoffeeOrder order;
	private CoffeeOrderService coffeeOrderService = new CoffeeOrderService();

	/**
	 * To create a new order on first access or when a previous order was
	 * confirmed.
	 */
	public void createNewOrderIfNeeded() {
		if (order == null) {
			order = coffeeOrderService.createNewOrder();
		}
	}

	/**
	 * To prepare an order for confirmation.
	 */
	public String makeOrder() {
		if (getOrderItemsWithNotZeroQuantity().isEmpty()) {
			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage(ResourceBundleUTF8.getUTF8Bundle().getString("order_empty")));
			return "coffee";
		}

		coffeeOrderService.prepareOrder(order,
				configController.getFreeCupParameter(),
				configController.getDeliveryCostParameter(),
				configController.getFreeDeliveryParameter());

		return "order";
	}

	public String confirmOrder() {
		try {
			coffeeOrderService.confirmOrder(order);
		} catch (CoffeeOrderServiceException e) {
			e.printStackTrace();
			return "error";
		} finally {
			order = null;
		}
		return "orderResult";
	}

	public List<CoffeeOrderItem> getOrderItemsWithNotZeroQuantity() {
		return order.getOrderItems().stream()
				.filter(item -> item.getQuantity() != 0)
				.collect(Collectors.toList());
	}

	public CoffeeOrder getOrder() {
		return order;
	}

	public void setOrder(CoffeeOrder order) {
		this.order = order;
	}

	public void setConfigController(ConfigController configController) {
		this.configController = configController;
	}

}

WebContent/view/coffee.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:of="http://omnifaces.org/functions">
<h:body>
	<ui:composition template="template/template.xhtml">
		<ui:define name="content">
			<h:outputScript
				library="js"
				name="jquery-3.1.1.min.js" />
			<h:outputScript
				library="js"
				name="coffee.js" />
			<f:event
				listener="#{orderController.createNewOrderIfNeeded}"
				type="preRenderView" />
			<div class="make-order-container">
				<ui:insert>
					<ui:include src="parts/offer.xhtml" />
				</ui:insert>
				<ui:insert>
					<ui:include src="parts/makeOrderControl.xhtml" />
				</ui:insert>
			</div>
			<div>
				<h:messages
					layout="table"
					styleClass="errors" />
			</div>
			<div class="coffee-container">
				<ui:repeat
					var="orderItem"
					value="#{orderController.order.orderItems}"
					varStatus="status">
					<table class="coffee #{orderItem.quantity > 0 ? 'coffee-selected' : ''}">
						<tr>
							<td>
								<h:outputText value="#{orderItem.coffeeType.name}" />
							</td>
						</tr>
						<tr>
							<td>
								<h:outputText
									styleClass="coffee-price"
									value="#{orderItem.coffeeType.price} TGR" />
							</td>
						</tr>
						<tr>
							<td>
								<table class="coffee-quantity-controls">
									<tr>
										<td>
											<input
												type="button"
												value="&nbsp;&lt;&nbsp;"
												class="coffee-less" />
										</td>
										<td>
											<h:inputText
												type="text"
												value="#{orderItem.quantity}"
												size="3"
												styleClass="coffee-quantity #{component.valid ? '' : 'input-error'}"
												converterMessage="#{of:format1(strings['validation_qty_format'], configController.maxCupsPerTypeParameter.value)}"
												validatorMessage="#{of:format1(strings['validation_qty_format'], configController.maxCupsPerTypeParameter.value)}">
												<f:validateLongRange
													minimum="0"
													maximum="#{configController.maxCupsPerTypeParameter.value}"></f:validateLongRange>
											</h:inputText>
										</td>
										<td>
											<input
												type="button"
												value="&nbsp;&gt;&nbsp;"
												class="coffee-more" />
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</ui:repeat>
			</div>
			<div class="make-order-container">
				<ui:insert>
					<ui:include src="parts/makeOrderControl.xhtml" />
				</ui:insert>
				<ui:insert>
					<ui:include src="parts/offer.xhtml" />
				</ui:insert>
			</div>
		</ui:define>
	</ui:composition>
</h:body>
</html>

WebContent/view/error.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
	<ui:composition template="template/template.xhtml">
		<ui:define name="content">
			<div class="errors">
				<h:outputText value="#{strings['error']}" />
			</div>
		</ui:define>
	</ui:composition>
</h:body>
</html>

WebContent/view/order.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:of="http://omnifaces.org/functions">
<h:body>
	<ui:composition template="template/template.xhtml">
		<ui:define name="content">
			<div class="order-container">
				<table class="order">
					<tr>
						<th>#{strings['order_type']}</th>
						<th>#{strings['order_qty']}</th>
						<th>#{strings['order_price_per_cup']}</th>
						<th>#{strings['order_price']}</th>
					</tr>
					<ui:repeat
						var="orderItem"
						value="#{orderController.orderItemsWithNotZeroQuantity}">
						<tr>
							<td>#{orderItem.coffeeType.name}</td>
							<td>
								#{orderItem.quantity}
								<h:outputText
									rendered="#{orderItem.freeQuantity > 0}"
									value=" (#{orderItem.freeQuantity} #{strings['order_free']})" />
							</td>
							<td>
								<h:outputText value="#{orderItem.coffeeType.price} TGR" />
							</td>
							<td>
								<h:outputText value="#{orderItem.cost} TGR" />
							</td>
						</tr>
					</ui:repeat>
					<tr>
						<td
							colspan="3"
							align="right">#{strings['order_subtotal']}</td>
						<td>
							<h:outputText value="#{orderController.order.subtotalCost} TGR" />
						</td>
					</tr>
					<tr>
						<td
							colspan="3"
							align="right">#{strings['order_delivery']}</td>
						<td>
							<h:outputText value="#{orderController.order.deliveryCost} TGR" />
						</td>
					</tr>
					<tr>
						<td
							colspan="3"
							align="right">#{strings['order_total']}</td>
						<td>
							<h:outputText value="#{orderController.order.totalCost} TGR" />
						</td>
					</tr>
					<tr>
						<td colspan="4">
							<table class="payer-info">
								<tr>
									<td>#{strings['order_name']}</td>
									<td>
										<h:inputText
											id="name"
											value="#{orderController.order.payerName}"
											validatorMessage="#{of:format1(strings['validation_maximum_length'], 100)}">
											<f:validateLength maximum="100" />
										</h:inputText>
									</td>
								</tr>
								<tr>
									<td colspan="2">
										<h:message
											styleClass="error"
											for="name" />
									</td>
								</tr>
								<tr>
									<td>#{strings['order_address']}</td>
									<td>
										<h:inputText
											id="deliveryAddress"
											value="#{orderController.order.deliveryAddress}"
											required="true"
											validatorMessage="#{of:format1(strings['validation_maximum_length'], 200)}"
											requiredMessage="#{strings['validation_address_required']}">
											<f:validateLength maximum="200" />
										</h:inputText>
									</td>
								</tr>
								<tr>
									<td colspan="2">
										<h:message
											styleClass="error"
											for="deliveryAddress" />
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
				<div class="order-controls-container">
					<h:button
						value="~ #{strings['order_back']} ~"
						styleClass="go-back button"
						outcome="/view/coffee" />
					<h:commandButton
						value="~ #{strings['order_confirm']} ~"
						styleClass="submit-order button"
						action="#{orderController.confirmOrder}" />
				</div>
			</div>
		</ui:define>
	</ui:composition>
</h:body>
</html>

WebContent/view/orderResult.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
	<ui:composition template="template/template.xhtml">
		<ui:define name="content">
			<div class="order-result-container">
				<h:outputText
					value="#{strings['order_result']}"
					styleClass="order-result" />
				<h:button
					outcome="/view/coffee"
					value="~ #{strings['order_more']} ~"
					styleClass="make-another-order button" />
			</div>
		</ui:define>
	</ui:composition>
</h:body>
</html>