src/main/java/controller/ConfigController.java
package controller;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;

import model.ConfigParameter;
import service.ConfigService;

@ApplicationScoped
@ManagedBean
public class ConfigController {
	
	private ConfigService configService = new ConfigService();

	public ConfigParameter getFreeCupParameter() {
		return configService.getConfigParameter("n");
	}

	public ConfigParameter getDeliveryCostParameter() {
		return configService.getConfigParameter("m");
	}

	public ConfigParameter getFreeDeliveryParameter() {
		return configService.getConfigParameter("x");
	}

	public ConfigParameter getMaxCupsPerTypeParameter() {
		return configService.getConfigParameter("maxCupsPerType");
	}

}

WebContent/view/parts/makeOrderControl.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
	<h:commandButton
		value="~ #{strings['make_order']} ~"
		styleClass="make-order button"
		action="#{orderController.makeOrder}" />
</h:body>
</html>

WebContent/view/parts/offer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
	<h:outputFormat
		styleClass="offer"
		value="#{strings['offer_cup']}">
		<f:param value="#{configController.freeCupParameter.value}" />
	</h:outputFormat>
	<h:outputFormat
		styleClass="offer"
		value="#{strings['offer_delivery']}">
		<f:param value="#{configController.freeDeliveryParameter.value}" />
	</h:outputFormat>
</h:body>
</html>